version: '3.1'
services:
  webhook_payload:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/usr/src/app
     - /etc/localtime:/etc/localtime
    environment:
     - ENV=development
     - PORT=5000
     - MONGO_URI=mongodb://root:example@mongodb:27017/
     - MONGO_DBNAME=webhook_payload
     - SECRET='webhook_payload'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod
  mongo-express:
    image: mongo-express
    container_name: mongo-express-ui
    restart: always
    ports:
      - "8481:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
